# Generated by Django 4.1 on 2022-09-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options_alter_todo_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['title'], 'verbose_name_plural': 'Todoss'},
        ),
    ]
