# Generated by Django 4.1 on 2022-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='name_first', max_length=30)),
                ('last_name', models.CharField(help_text='Please Enter Your Last Name', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(default='fscohort/avatar.jpg', upload_to='media/')),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Prefer Not Say')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Studentsss',
                'db_table': 'number',
            },
        ),
    ]
