"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path       

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# projenin bulundugu dizini gösterir
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
## django kendisi unique olarak üretir. django da güvenlik önemli 
# kendisi güvenlik icin her bir proje icin üretir. google kendimiz de secret key üreten sitelerden elde edebiliriz. 
SECRET_KEY = 'django-insecure-2z$8!*$z6**e73_!99v*w82*37cqx04#1-nibv$91-l510abv*'

# SECURITY WARNING: don't run with debug turned on in production!
# debug da django nun avantajlarindan biridir. 
# ayrintili hata mesajlarindan istifade etmek icin   true. bu udrumda sadece 404 hatasi almayiz detayli mesaj aliriz. proje canliya ciktiya ciktiginda bize yardimci olan bu bilgler baskasi eline gecmesin diye false olur. 
DEBUG = True

## hangi domain lerden erisilmesini istiyorsak. örnek:
# ALLOWED_HOSTS = ["www.google.com"]
# kullanim olarak ["*"] sekli de vardir. herseye izin ver
# birden cok url yazacak isek aralara , konulur.

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions', # oturumlari yöntir farkli tab a gecsek de cerezler avsitasi ile calismaya devam etmesini saglar.
    'django.contrib.messages',
    'django.contrib.staticfiles',

        ## my Apps:
    'firstApp',
    'secondApp',
    'thirdApp',
    'rest_framework',

]


## request response arasi islemler bazi katmanlardan gecer. bunlar default
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

    #  default olarak ilk olarak main.urls e git

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

## django default olarak sqlite ile gelir. lokal de calisma avantaji vardir sqlite in . bu nedenle mobil telefonlarda kullanilir. 
## mesela postgre kullanmak istersek internetten hazir kodunu alip buraya yapistiriyoruz. 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

## django nun bize sagladigi bir baska avantaj: 

AUTH_PASSWORD_VALIDATORS = [
        ## diger bilgilerimizle benzer password 
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
        ### cok kullanilan password ler
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
